## 1. try
**Python** 使用 try/except  语句处理异常
```python
try:
    # 代码
    
except: 
    
    # 异常处理代码
    
else:
    
    # 没有发生异常时执行的代码
    
finally:
    
    # 无论是否发生异常都会执行的代码
```
## 
## 2. except


**< except** 异常类型名 : >   根据异常类型匹配异常： 
< **except** : > 匹配所有异常
```python
try:
    ####
except RuntimeError:
    ####
except TypeError:
    ####
except (NameError,SSLError):
    ####
except:
    # 匹配所有异常 
    print("Unexpected error:", sys.exc_info()[0])
```
如果一个异常没有与任何的 **except** 匹配，那么这个异常将会传递给上层的 try 调用中。
**​**

**except**，**as** 用于获取异常对象
```python
try:
    ####
except RuntimeError as err:       # 捕获err异常对象
    print(err)        
```
 
## 3. raise 


**raise** 关键字用于抛出异常
```python
raise [Exception [, args [, traceback]]]

# 抛出异常

x = 10
if x > 5:
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))   # 大于5抛出异常
    
# 在except语句中可以使用raise抛出在当前阶段不需要处理的异常
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    raise
```


## 4. 自定义异常


我们可以通过继承 **Exception** 类来实现自定义异常
​

```python
class MyError(Exception):
    def __int__(self,value):
        self.value = value
    def __str__(self):
        return repr(self.value)
```


## 5. with 预定义清理行为


```python
# 当发生异常时，文件没有关闭
for line in open("myfile.txt"):
    print(line, end="")
    
# 使用with 预定义清理行为

with open("myfile.txt") as f:
    for line in f:
        print(line, end="")

    
 
```
